student_registration/student/urls.py
import imp
from django.urls import path
from . import views
app_name='student'
urlpatterns=[
    path('',views.Home.as_view(),name='home'),
    path('add/',views.FormView.as_view(),name='form'),
    path('update/<int:pk>',views.Update.as_view(),name='update'),
    path('delete/<int:pk>',views.Delete.as_view(),name='delete'),
]

student_registration/student_registration/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/',include('student.urls')),
]

student_registration/student/models.py
from django.db import models
from django.forms import IntegerField

# Create your models here.
class StudentModel(models.Model):
    name=models.CharField(max_length=30)
    email=models.EmailField()
    phone=models.PositiveBigIntegerField(max_length=10)
    Class=models.IntegerField()
    marks=models.PositiveIntegerField()

student_registration/student/views.py
from django.shortcuts import render
from django.views.generic import CreateView,TemplateView,ListView,UpdateView,DeleteView
from . import models
class FormView(CreateView):
    model=models.StudentModel
    fields="__all__"
    success_url="/student/"
class Home(ListView):
    model=models.StudentModel
    context_object_name='student_list'
class Update(UpdateView):
    model=models.StudentModel
    fields="__all__"
    success_url="/student/"
class Delete(DeleteView):
    model=models.StudentModel
    success_url="/student/"

student_registration/student/templates/student/StudentModel_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <style>
        body{
            background-color:#7cffcb;
background-image:linear-gradient(315deg, #7cffcb 0%, #74f2ce 74%);

        }
        .container1{
            background-color: rgb(255, 255, 255);
            width:50%;
            position:absolute;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            top: 50%;
            left: 50%;
            transform: translate(-50%,-50%);
            height: 50%;
            box-shadow: 0px 4px 8px 0px rgba(0,0,0,0.2);
        }
        .btn{
            width:300px;
        }
    </style>
</head>
<body>
    <div class="container1">
        <h2 style="color: rgb(26, 25, 25);">Are you sure you want to delete?</h2>
        <p>{{student_list.name}}</p>
    <br><br><br>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="YES!" class="btn btn-success">
</form>
    </div>
    
</body>
</html>

student_registration/student/templates/student/StudentModel_form.html
{% extends "navbar.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="mb-3 container row align-items-center justify-content-center form-control">
            <label for="" class="form-label"><span style="color: #198754">{{field.label_tag}}</span></label>
            <div class="container\">{{field}}</div>
        </div>
           
        {% endfor %}
        <input type="submit" value="Submit" class="btn btn-success">
    </form>
   
{% endblock %}

student_registration/student/templates/student/StudentModel_list.html
{% extends "navbar.html" %}

{% block content %}
      <br><br><br><br>
      <table class="table table-striped table-dark">
        <thead>
          <tr>
            <th scope="col"><span style="color:#198754 ;">#</span></th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Marks</th>
            <th scope="col">Class</th>
            <th scope="col">Options</th>
          </tr>
        </thead>
        <tbody>
          {% for student in student_list %}
          <tr>
            <th scope="row">{{student.id}}</th>
            <td>{{student.name}}</td>
            <td>{{student.email}}</td>
            <td>{{student.marks}}</td>
            <td>{{student.Class}}</td>
            <td><a href="/student/delete/{{student.id}}"><button class="btn btn-danger">Delete</button></a>&nbsp;&nbsp;&nbsp;&nbsp;
              <a href="/student/update/{{student.id}}"><button class="btn btn-success">Edit</button></td></a>
          </tr>
        {% endfor %}
        </tbody>
      </table>
{% endblock %}

student_registration/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<style>
    .nav-item{
        margin-left: 70px;
    }
</style>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"><span style="color: #198754; font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif; font-weight: bold; font-size: 15px;">STUDENT REGISTRATION</span></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'student:home' %}"><span style="color: white;">Home</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'student:form' %}"><span style="color: white;">Add Student</span></a>
              </li>
             
           
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    {% block content %}

    {% endblock %}
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

</body>
</html>